env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - PROJECT_NAME=gimps
  - PROJECT_USER=xrstf

builds:
  - id: gimps-amd64
    binary: gimps
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: gimps-darwin-amd64
    binary: gimps
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: gimps-windows-amd64
    binary: gimps
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: xrstf
    name: gimps
